# Use official Node.js image
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install all dependencies (including dev dependencies)
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the default Strapi port
EXPOSE 1337

# Start the Strapi app in development mode
CMD ["npm", "run", "develop"] 