name: CD - Deploy with Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download image tag
        uses: actions/download-artifact@v4
        with:
          name: image-tag
          path: ./artifacts

      - name: Set IMAGE_TAG env
        run: |
          echo "IMAGE_TAG=$(cat ./artifacts/image_tag.txt)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform2_task5
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform2_task5
        run: terraform plan -var="image_tag=$IMAGE_TAG"

      - name: Terraform Apply
        working-directory: terraform2_task5
        run: terraform apply -auto-approve -var="image_tag=$IMAGE_TAG"
