name: CI pipeline - Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "tag=gh-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/strapi:gh-${GITHUB_SHA::7} \
            ./strapi-app

      - name: Save image tag
        run: echo "${{ steps.vars.outputs.tag }}" > image_tag.txt

      - name: Upload image tag
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-tag
          path: image_tag.txt